using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace MoreBuilding
{
    public enum Index
    {
        ScrapMetal_Upgrade = 160546,
        Brick_Upgrade = 160547,
        SolidMetal_Upgrade = 160548,
        Glass_Upgrade = 160550,
        ScrapMetal_Foundation = 160000,
        ScrapMetal_TriangleFoundation,
        ScrapMetal_TriangleFoundationMirrored,
        ScrapMetal_Floor,
        ScrapMetal_TriangleFloor,
        ScrapMetal_TriangleFloorMirrored,
        ScrapMetal_Wall,
        ScrapMetal_WallHalf,
        ScrapMetal_WallV,
        ScrapMetal_WallSlope,
        ScrapMetal_WallSlopeInverted,
        ScrapMetal_Fence,
        ScrapMetal_Gate,
        ScrapMetal_Door,
        ScrapMetal_Window,
        ScrapMetal_WindowHalf,
        ScrapMetal_RoofStraight,
        ScrapMetal_RoofCorner,
        ScrapMetal_RoofCornerInverted,
        ScrapMetal_RoofV0,
        ScrapMetal_RoofV1,
        ScrapMetal_RoofV2I,
        ScrapMetal_RoofV2L,
        ScrapMetal_RoofV3,
        ScrapMetal_RoofV4,
        ScrapMetal_Pillar,
        ScrapMetal_PillarHalf,
        ScrapMetal_PillarHorizontal,
        ScrapMetal_PillarHorizontalHalf,
        ScrapMetal_Ladder,
        ScrapMetal_LadderHalf,
        ScrapMetal_FloorHalf,
        ScrapMetal_TriangleFloorHalf,
        ScrapMetal_TriangleFloorHalfMirrored,
        ScrapMetal_Stair,
        ScrapMetal_StairHalf,
        SolidMetal_Foundation = 320000,
        SolidMetal_TriangleFoundation,
        SolidMetal_TriangleFoundationMirrored,
        SolidMetal_Floor,
        SolidMetal_TriangleFloor,
        SolidMetal_TriangleFloorMirrored,
        SolidMetal_Wall,
        SolidMetal_WallHalf,
        SolidMetal_WallV,
        SolidMetal_WallSlope,
        SolidMetal_WallSlopeInverted,
        SolidMetal_Fence,
        SolidMetal_Gate,
        SolidMetal_Door,
        SolidMetal_Window,
        SolidMetal_WindowHalf,
        SolidMetal_RoofStraight,
        SolidMetal_RoofCorner,
        SolidMetal_RoofCornerInverted,
        SolidMetal_RoofV0,
        SolidMetal_RoofV1,
        SolidMetal_RoofV2I,
        SolidMetal_RoofV2L,
        SolidMetal_RoofV3,
        SolidMetal_RoofV4,
        SolidMetal_Pillar,
        SolidMetal_PillarHalf,
        SolidMetal_PillarHorizontal,
        SolidMetal_PillarHorizontalHalf,
        SolidMetal_Ladder,
        SolidMetal_LadderHalf,
        SolidMetal_FloorHalf,
        SolidMetal_TriangleFloorHalf,
        SolidMetal_TriangleFloorHalfMirrored,
        SolidMetal_Stair,
        SolidMetal_StairHalf,
        Glass_Foundation = 6970,
        Glass_TriangleFoundation,
        Glass_TriangleFoundationMirrored, // Legacy from glass walls mod. Not used
        Glass_Floor,
        Glass_TriangleFloor,
        Glass_TriangleFloorMirrored, // Legacy from glass walls mod. Not used
        Glass_Wall,
        Glass_WallHalf,
        Glass_WallSlope,
        Glass_WallV,
        Glass_WallSlopeInverted,
        Glass_RoofStraight,
        Glass_RoofCorner,
        Glass_RoofCornerInverted,
        Glass_RoofV2I,
        Glass_RoofV2L,
        Glass_RoofV3,
        Glass_RoofV4,
        Glass_RoofV1,
        Glass_RoofV0,
        Glass_Pillar,
        Glass_PillarHalf,
        Glass_PillarHorizontal,
        Glass_PillarHorizontalHalf,
        Glass_Ladder,
        Glass_LadderHalf,
        Glass_Door,
        Brick_Foundation = 160100,
        Brick_TriangleFoundation,
        Brick_TriangleFoundationMirrored,
        Brick_Floor,
        Brick_TriangleFloor,
        Brick_TriangleFloorMirrored,
        Brick_Wall,
        Brick_WallHalf,
        Brick_WallV,
        Brick_WallSlope,
        Brick_WallSlopeInverted,
        Brick_Fence,
        Brick_Gate,
        Brick_Door,
        Brick_Window,
        Brick_WindowHalf,
        Brick_RoofStraight,
        Brick_RoofCorner,
        Brick_RoofCornerInverted,
        Brick_RoofV0,
        Brick_RoofV1,
        Brick_RoofV2I,
        Brick_RoofV2L,
        Brick_RoofV3,
        Brick_RoofV4,
        Brick_Pillar,
        Brick_PillarHalf,
        Brick_PillarHorizontal,
        Brick_PillarHorizontalHalf,
        Brick_Ladder,
        Brick_LadderHalf,
        Brick_FloorHalf,
        Brick_TriangleFloorHalf,
        Brick_TriangleFloorHalfMirrored,
        Brick_Stair,
        Brick_StairHalf
    }
}
